### PR TITLE
fix: Tools 2512 incorrect enable compression

### PR DESCRIPTION
**Pull request by jdogmcsteezy**
We were displaying the message for the namespace context when it should have been for the xdr/dc/namespace context

### CODE REVIEW

**Review by dwelch-spike — APPROVED** [review]
LGTM

**Review by dwelch-spike — APPROVED** [review]
LGTM

**Comment by dwelch-spike** [comment]
Please have a look at the failing tests before merging

**Comment by jdogmcsteezy** [comment]
Talked with @dwelch-spike. Might be a good idea to remove these hints. People might come to expect this too much from asadm.

**Review by dwelch-spike — APPROVED** [review]
LGTM, please check the test issue before merging.

**Pull request merged**
